id: I65BB3693
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T10:35:53+00:00'
last_modified: '2022-06-07T22:05:59.560730+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29263
  title: ཏུན་ཧོང་ཡིག་རྙིང་ལས་བྱུང་བའི་བོད་ཀྱི་གནའ་རབས་སྨོན་ལམ་དང་དེའི་མཆན་འགྲེལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    945B:
      image_group_id: I1KG23202
      title: ''
      total_pages: 114
      order: 1
      base_file: 945B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
