id: P004337
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 11:12:22.481816
source_metadata:
  id: bdr:W29263
  title: ཏུན་ཧོང་ཡིག་རྙིང་ལས་བྱུང་བའི་བོད་ཀྱི་གནའ་རབས་སྨོན་ལམ་དང་དེའི་མཆན་འགྲེལ།
  author: ''
  volumes:
    8f3bf555630e4f1eaa27f8b2bbf611cf:
      image_group_id: I1KG23202
      title: ''
      volume_number: 1
      total_pages: 114
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
