id: P004337
initial_creation_type: ocr
source_metadata:
  id: bdr:W29263
  title: ཏུན་ཧོང་ཡིག་རྙིང་ལས་བྱུང་བའི་བོད་ཀྱི་གནའ་རབས་སྨོན་ལམ་དང་དེའི་མཆན་འགྲེལ།
  author: ''
  volumes:
    8f3bf555630e4f1eaa27f8b2bbf611cf:
      image_group_id: I1KG23202
      title: ''
      volume_number: 1
      total_pages: 114
